language: java

jdk:
  - openjdk14

sudo: false # faster builds

script: 
  - "./mvnw clean install"
  - "./mvnw -pl maven-plugin site install"

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
